const s = {
  // ── Layout ────────────────────────────────────────────────────────
  page: { padding: "1.75rem 2rem 2.5rem", maxWidth: "1280px", margin: "0 auto", fontFamily: "'Segoe UI', system-ui, sans-serif" },
  heading: { fontSize: "1.45rem", fontWeight: 800, color: "#0f172a", marginBottom: "0.2rem" },
  subheading: { fontSize: "0.865rem", color: "#64748b", marginBottom: "1.6rem" },

  // ── Summary Stats Row ─────────────────────────────────────────────
  statsRow: {
    display: "grid",
    gridTemplateColumns: "repeat(4, 1fr)",
    gap: "1rem",
    marginBottom: "1.75rem",
  },
  statCard: (bg, accent) => ({
    background: "#fff",
    borderRadius: "16px",
    padding: "1.2rem 1.4rem",
    display: "flex",
    flexDirection: "column",
    gap: "0.5rem",
    boxShadow: "0 2px 12px rgba(0,0,0,0.06)",
    border: "1px solid #f1f5f9",
    borderTop: `3px solid ${accent}`,
    position: "relative",
    overflow: "hidden",
  }),
  statLabel: { fontSize: "0.72rem", fontWeight: 700, color: "#64748b", textTransform: "uppercase", letterSpacing: "0.07em" },
  statValue: (color) => ({ fontSize: "1.6rem", fontWeight: 800, color: color, lineHeight: 1.1 }),

  // ── Toolbar ───────────────────────────────────────────────────────
  toolbar: {
    display: "flex",
    alignItems: "center",
    gap: "0.75rem",
    marginBottom: "1.25rem",
    flexWrap: "wrap",
    background: "#fff",
    border: "1px solid #e2e8f0",
    borderRadius: "14px",
    padding: "0.75rem 1rem",
    boxShadow: "0 1px 4px rgba(0,0,0,0.04)",
  },
  searchWrap: {
    display: "flex",
    flex: 1,
    minWidth: "220px",
    maxWidth: "380px",
    border: "1px solid #e2e8f0",
    borderRadius: "10px",
    overflow: "hidden",
    background: "#f8fafc",
  },
  searchInput: {
    border: "none",
    outline: "none",
    padding: "0.55rem 0.9rem",
    fontSize: "0.875rem",
    flex: 1,
    background: "transparent",
    color: "#0f172a",
  },
  searchBtn: {
    background: "#6366f1",
    color: "#fff",
    border: "none",
    padding: "0.55rem 1rem",
    cursor: "pointer",
    fontWeight: 700,
    fontSize: "0.82rem",
  },
  filterChip: (active) => ({
    padding: "0.48rem 1.1rem",
    borderRadius: "9999px",
    cursor: "pointer",
    fontWeight: 700,
    fontSize: "0.82rem",
    border: "1.5px solid " + (active ? "#6366f1" : "#e2e8f0"),
    background: active ? "#eef2ff" : "#fff",
    color: active ? "#4f46e5" : "#64748b",
  }),
  addBtn: {
    marginLeft: "auto",
    background: "linear-gradient(135deg, #4f46e5, #7c3aed)",
    color: "#fff",
    border: "none",
    borderRadius: "10px",
    padding: "0.55rem 1.35rem",
    cursor: "pointer",
    fontWeight: 700,
    fontSize: "0.875rem",
    display: "flex",
    alignItems: "center",
    gap: "0.4rem",
    boxShadow: "0 4px 12px rgba(79,70,229,0.3)",
  },

  // ── Table Card ────────────────────────────────────────────────────
  tableCard: {
    background: "#fff",
    borderRadius: "16px",
    boxShadow: "0 4px 20px rgba(0,0,0,0.07)",
    border: "1px solid #e2e8f0",
    overflow: "hidden",
  },
  tableHead: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "1rem 1.5rem",
    borderBottom: "1px solid #f1f5f9",
    background: "#fafbff",
  },
  tableTitle: { fontSize: "0.95rem", fontWeight: 700, color: "#0f172a" },
  countBadge: {
    background: "#eef2ff",
    color: "#4f46e5",
    borderRadius: "9999px",
    padding: "0.15rem 0.7rem",
    fontSize: "0.75rem",
    fontWeight: 800,
    marginLeft: "0.5rem",
  },
  table: { width: "100%", borderCollapse: "collapse" },
  th: {
    textAlign: "left",
    padding: "0.75rem 1.25rem",
    background: "#f8fafc",
    fontSize: "0.7rem",
    fontWeight: 800,
    color: "#94a3b8",
    borderBottom: "1px solid #e2e8f0",
    whiteSpace: "nowrap",
    textTransform: "uppercase",
    letterSpacing: "0.07em",
  },
  td: {
    padding: "1rem 1.25rem",
    fontSize: "0.875rem",
    color: "#334155",
    borderBottom: "1px solid #f8fafc",
    verticalAlign: "middle",
  },
  tdRed: {
    padding: "1rem 1.25rem",
    fontSize: "0.875rem",
    color: "#dc2626",
    borderBottom: "1px solid #f8fafc",
    verticalAlign: "middle",
    fontWeight: 700,
  },

  // ── Customer Name Cell ────────────────────────────────────────────
  nameCell: { display: "flex", alignItems: "center", gap: "0.85rem" },
  avatar: {
    width: "40px",
    height: "40px",
    borderRadius: "12px",
    background: "linear-gradient(135deg, #4f46e5, #8b5cf6)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#fff",
    fontWeight: 800,
    fontSize: "1rem",
    flexShrink: 0,
    boxShadow: "0 3px 8px rgba(79,70,229,0.25)",
  },
  custName:  { fontWeight: 700, color: "#0f172a", fontSize: "0.875rem" },
  custPhone: { fontSize: "0.74rem", color: "#94a3b8", marginTop: "2px" },

  // ── Status / badges ───────────────────────────────────────────────
  statusBadge: (cleared) => ({
    display: "inline-flex",
    alignItems: "center",
    gap: "0.25rem",
    borderRadius: "9999px",
    padding: "0.25rem 0.8rem",
    fontSize: "0.73rem",
    fontWeight: 700,
    background: cleared ? "#f0fdf4" : "#fff7ed",
    color: cleared ? "#16a34a" : "#ea580c",
    border: "1px solid " + (cleared ? "#bbf7d0" : "#fed7aa"),
  }),
  amountBadge: (hasBalance) => ({
    fontWeight: 700, color: hasBalance ? "#dc2626" : "#16a34a",
  }),

  // ── Action buttons ────────────────────────────────────────────────
  actionWrap: { display: "flex", gap: "0.4rem", alignItems: "center" },
  viewBtn: {
    border: "none",
    background: "#eef2ff",
    color: "#4f46e5",
    borderRadius: "8px",
    padding: "0.38rem 0.75rem",
    cursor: "pointer",
    fontSize: "0.8rem",
    fontWeight: 700,
    display: "flex",
    alignItems: "center",
    gap: "0.25rem",
  },
  editBtn:   { border: "none", background: "#fefce8", color: "#ca8a04", borderRadius: "8px", padding: "0.38rem 0.6rem", cursor: "pointer", fontSize: "0.82rem", fontWeight: 600 },
  deleteBtn: { border: "none", background: "#fef2f2", color: "#ef4444", borderRadius: "8px", padding: "0.38rem 0.6rem", cursor: "pointer", fontSize: "0.82rem", fontWeight: 600 },

  // ── Pagination ────────────────────────────────────────────────────
  paginationWrap: {
    display: "flex",
    justifyContent: "flex-end",
    alignItems: "center",
    gap: "0.35rem",
    padding: "0.85rem 1.25rem",
    borderTop: "1px solid #f1f5f9",
    background: "#fafbff",
  },
  pageBtn: (active) => ({
    border: active ? "none" : "1px solid #e2e8f0",
    background: active ? "#4f46e5" : "#fff",
    color: active ? "#fff" : "#475569",
    borderRadius: "8px",
    padding: "0.32rem 0.72rem",
    cursor: "pointer",
    fontWeight: active ? 800 : 500,
    fontSize: "0.82rem",
    minWidth: "32px",
    textAlign: "center",
    boxShadow: active ? "0 2px 8px rgba(79,70,229,0.3)" : "none",
  }),

  empty: {
    textAlign: "center",
    padding: "4rem 1rem",
    color: "#94a3b8",
    fontSize: "0.9rem",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "0.5rem",
  },
  loadingWrap: { textAlign: "center", padding: "3.5rem 1rem", color: "#94a3b8", fontSize: "0.9rem" },

  // ── Modal ─────────────────────────────────────────────────────────
  overlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(15,23,42,0.5)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1000,
    backdropFilter: "blur(4px)",
  },
  modal: {
    background: "#fff",
    borderRadius: "20px",
    boxShadow: "0 20px 60px rgba(0,0,0,0.2)",
    padding: "2rem 2rem 1.75rem",
    width: "min(540px, 94vw)",
    maxHeight: "90vh",
    overflowY: "auto",
  },
  modalTitle: {
    fontSize: "1.15rem",
    fontWeight: 800,
    color: "#0f172a",
    marginBottom: "1.5rem",
    paddingBottom: "0.9rem",
    borderBottom: "1px solid #f1f5f9",
  },
  formGroup: { display: "flex", flexDirection: "column", gap: "0.4rem", marginBottom: "1.1rem" },
  label: { fontSize: "0.8rem", fontWeight: 700, color: "#374151" },
  input: {
    padding: "0.62rem 0.9rem",
    borderRadius: "10px",
    border: "1.5px solid #e2e8f0",
    fontSize: "0.9rem",
    outline: "none",
    color: "#0f172a",
  },
  select: {
    padding: "0.62rem 0.9rem",
    borderRadius: "10px",
    border: "1.5px solid #e2e8f0",
    fontSize: "0.9rem",
    outline: "none",
    background: "#fff",
    color: "#0f172a",
  },
  textarea: {
    padding: "0.62rem 0.9rem",
    borderRadius: "10px",
    border: "1.5px solid #e2e8f0",
    fontSize: "0.9rem",
    outline: "none",
    resize: "vertical",
    minHeight: "75px",
    fontFamily: "'Segoe UI', sans-serif",
    color: "#0f172a",
  },
  errorMsg: {
    color: "#dc2626",
    fontSize: "0.82rem",
    marginTop: "0.4rem",
    background: "#fef2f2",
    border: "1px solid #fecaca",
    borderRadius: "8px",
    padding: "0.5rem 0.75rem",
  },
  modalActions: { display: "flex", justifyContent: "flex-end", gap: "0.75rem", marginTop: "1.5rem" },
  cancelBtn: {
    padding: "0.55rem 1.35rem",
    borderRadius: "10px",
    border: "1.5px solid #e2e8f0",
    background: "#fff",
    color: "#374151",
    fontWeight: 700,
    cursor: "pointer",
    fontSize: "0.875rem",
  },
  submitBtn: {
    padding: "0.55rem 1.6rem",
    borderRadius: "10px",
    border: "none",
    background: "linear-gradient(135deg, #4f46e5, #7c3aed)",
    color: "#fff",
    fontWeight: 800,
    cursor: "pointer",
    fontSize: "0.875rem",
    boxShadow: "0 4px 12px rgba(79,70,229,0.3)",
  },

  // ── Detail page ───────────────────────────────────────────────────
  backBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: "0.4rem",
    background: "#fff",
    border: "1.5px solid #e2e8f0",
    borderRadius: "10px",
    padding: "0.45rem 1rem",
    cursor: "pointer",
    fontSize: "0.85rem",
    color: "#374151",
    fontWeight: 700,
    marginBottom: "1.25rem",
    boxShadow: "0 1px 4px rgba(0,0,0,0.05)",
  },
  detailGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: "1.5rem", marginBottom: "1.5rem" },
  infoCard: {
    background: "#fff",
    borderRadius: "16px",
    boxShadow: "0 4px 20px rgba(0,0,0,0.07)",
    border: "1px solid #e2e8f0",
    padding: "1.6rem",
  },
  infoCardTitle: {
    fontSize: "0.7rem",
    fontWeight: 800,
    color: "#94a3b8",
    textTransform: "uppercase",
    letterSpacing: "0.08em",
    marginBottom: "1.1rem",
  },
  infoRow: { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "0.75rem", paddingBottom: "0.75rem", borderBottom: "1px dashed #f1f5f9" },
  infoLabel: { fontSize: "0.83rem", color: "#64748b", fontWeight: 500 },
  infoValue: { fontSize: "0.9rem", fontWeight: 700, color: "#0f172a" },
  balanceValue: (hasBalance) => ({
    fontSize: "1.15rem", fontWeight: 800, color: hasBalance ? "#dc2626" : "#16a34a",
  }),
  balanceAlert: {
    background: "#fef2f2",
    border: "1px solid #fecaca",
    borderRadius: "12px",
    padding: "0.75rem 1rem",
    marginTop: "0.75rem",
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
    fontSize: "0.85rem",
    color: "#dc2626",
    fontWeight: 600,
  },
  clearedAlert: {
    background: "#f0fdf4",
    border: "1px solid #bbf7d0",
    borderRadius: "12px",
    padding: "0.75rem 1rem",
    marginTop: "0.75rem",
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
    fontSize: "0.85rem",
    color: "#16a34a",
    fontWeight: 600,
  },
  payBtn: {
    flex: 1,
    marginTop: "0.5rem",
    padding: "0.7rem",
    background: "linear-gradient(135deg, #4f46e5, #7c3aed)",
    color: "#fff",
    border: "none",
    borderRadius: "12px",
    cursor: "pointer",
    fontWeight: 800,
    fontSize: "0.875rem",
    boxShadow: "0 4px 12px rgba(79,70,229,0.3)",
  },

  // Transaction / payment section
  sectionCard: {
    background: "#fff",
    borderRadius: "16px",
    boxShadow: "0 4px 20px rgba(0,0,0,0.07)",
    border: "1px solid #e2e8f0",
    overflow: "hidden",
    marginBottom: "1.75rem",
  },
  sectionHead: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "1rem 1.5rem",
    borderBottom: "1px solid #f1f5f9",
    background: "#fafbff",
  },
  sectionTitle: { fontSize: "0.95rem", fontWeight: 700, color: "#0f172a" },
  sectionBadge: {
    background: "#eef2ff",
    color: "#4f46e5",
    borderRadius: "9999px",
    padding: "0.18rem 0.7rem",
    fontSize: "0.73rem",
    fontWeight: 800,
  },

  // Items mini list inside expanded row
  itemsTable: { width: "100%", borderCollapse: "collapse", background: "#f8fafc", fontSize: "0.82rem" },
  itemsTh: { padding: "0.5rem 1rem", fontWeight: 700, color: "#64748b", textAlign: "left", borderBottom: "1px solid #e2e8f0", fontSize: "0.72rem", textTransform: "uppercase", letterSpacing: "0.05em" },
  itemsTd: { padding: "0.5rem 1rem", color: "#334155", borderBottom: "1px solid #f1f5f9" },

  // Payment mode chip
  modeChip: (mode) => {
    const colors = {
      cash: ["#f0fdf4", "#16a34a"],
      upi:  ["#eff6ff", "#2563eb"],
      card: ["#fdf4ff", "#a855f7"],
    };
    const [bg, color] = colors[mode] || ["#f3f4f6", "#6b7280"];
    return {
      background: bg,
      color,
      borderRadius: "9999px",
      padding: "0.22rem 0.7rem",
      fontSize: "0.73rem",
      fontWeight: 700,
      border: "1px solid " + color + "33",
    };
  },

  // Remaining in red / cleared in green
  rBadge: (amount) => ({
    fontWeight: 700,
    color: parseFloat(amount) > 0 ? "#dc2626" : "#16a34a",
    fontSize: "0.875rem",
  }),
};

export default s;
