export default {
  page: { padding: "2rem", maxWidth: "1200px", margin: "0 auto" },
  headerDiv: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: "2rem" },
  backLink: { color: "#4f46e5", textDecoration: "none", fontSize: "1rem", fontWeight: 500, display: "inline-block", marginBottom: "0.5rem" },
  title: { fontSize: "1.8rem", fontWeight: 700, color: "#111827", margin: 0 },
  pSubtitle: { color: "#6b7280", margin: "0.2rem 0 0" },
  statsGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))", gap: "1rem", marginBottom: "2rem" },
  statCard: (bg, color) => ({ background: bg, padding: "1.5rem", borderRadius: "12px", border: `1px solid ${color}30` }),
  statLabel: { display: "block", fontSize: "0.9rem", color: "#6b7280", marginBottom: "0.5rem" },
  statValue: (color) => ({ display: "block", fontSize: "1.8rem", fontWeight: 700, color }),
  addPaymentBtn: { background: "#10b981", color: "white", padding: "0.6rem 1.2rem", borderRadius: "8px", border: "none", cursor: "pointer", fontWeight: 600 },
  overlay: { position: "fixed", inset: 0, background: "rgba(0,0,0,0.5)", display: "flex", alignItems: "center", justifyContent: "center", zIndex: 100 },
  modal: { background: "white", width: "400px", padding: "2rem", borderRadius: "12px", boxShadow: "0 10px 25px rgba(0,0,0,0.2)", maxHeight: "90vh", overflowY: "auto" },
  modalTitle: { margin: "0 0 1.5rem", fontSize: "1.25rem", fontWeight: 600 },
  formGroup: { marginBottom: "1rem" },
  label: { display: "block", marginBottom: "0.5rem", fontSize: "0.9rem", fontWeight: 500 },
  input: { width: "100%", padding: "0.6rem", border: "1px solid #d1d5db", borderRadius: "6px", fontSize: "1rem", boxSizing: "border-box" },
  textarea: { width: "100%", padding: "0.6rem", border: "1px solid #d1d5db", borderRadius: "6px", fontSize: "1rem", minHeight: "80px", fontFamily: "Arial", boxSizing: "border-box", fontFamily: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif" },
  select: { width: "100%", padding: "0.6rem", border: "1px solid #d1d5db", borderRadius: "6px", fontSize: "1rem", boxSizing: "border-box" },
  errorMsg: { color: "#dc2626", fontSize: "0.9rem", marginBottom: "1rem" },
  modalActions: { display: "flex", gap: "0.5rem", marginTop: "1.5rem" },
  cancelBtn: { flex: 1, padding: "0.6rem", border: "1px solid #d1d5db", background: "white", borderRadius: "6px", cursor: "pointer", fontWeight: 500 },
  submitBtn: { flex: 1, padding: "0.6rem", border: "none", background: "#4f46e5", color: "white", borderRadius: "6px", cursor: "pointer", fontWeight: 500 },
  twoCols: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: "2rem", "@media (max-width: 768px)": { gridTemplateColumns: "1fr" } },
  tableCard: { background: "white", border: "1px solid #e5e7eb", borderRadius: "12px", overflow: "hidden" },
  tableHeadText: { padding: "1rem 1.5rem", background: "#f9fafb", borderBottom: "1px solid #e5e7eb", fontWeight: 600, fontSize: "1.1rem" },
  table: { width: "100%", borderCollapse: "collapse" },
  th: { padding: "0.75rem 1rem", textAlign: "left", background: "#f9fafb", color: "#6b7280", fontSize: "0.85rem", textTransform: "uppercase", fontWeight: 600, borderBottom: "1px solid #e5e7eb" },
  td: { padding: "1rem", borderBottom: "1px solid #e5e7eb", color: "#374151" },
  emptyText: { padding: "2rem", textAlign: "center", color: "#6b7280" }
};
