const styles = {
  page: {
    minHeight: "100vh",
    backgroundColor: "#f0f2f5",
    padding: "2rem",
    fontFamily: "sans-serif",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "2rem",
  },
  title: { fontSize: "1.75rem", fontWeight: 700, color: "#1e1b4b" },
  backBtn: {
    padding: "0.5rem 1rem",
    borderRadius: "8px",
    border: "none",
    background: "#e0e7ff",
    color: "#4f46e5",
    fontWeight: 600,
    cursor: "pointer",
    textDecoration: "none",
    fontSize: "0.9rem",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
    background: "#fff",
    borderRadius: "12px",
    overflow: "hidden",
    boxShadow: "0 2px 12px rgba(0,0,0,0.07)",
  },
  th: {
    padding: "0.9rem 1rem",
    textAlign: "left",
    background: "#4f46e5",
    color: "#fff",
    fontWeight: 600,
    fontSize: "0.875rem",
  },
  td: {
    padding: "0.85rem 1rem",
    borderBottom: "1px solid #f3f4f6",
    fontSize: "0.9rem",
    color: "#374151",
  },
  trEven: { background: "#f9fafb" },
  gstOn:  { color: "#059669", fontWeight: 600 },
  gstOff: { color: "#dc2626", fontWeight: 600 },
  viewBtn: {
    padding: "0.4rem 0.9rem",
    borderRadius: "6px",
    border: "none",
    background: "#4f46e5",
    color: "#fff",
    fontWeight: 600,
    cursor: "pointer",
    textDecoration: "none",
    fontSize: "0.8rem",
  },
  error: { color: "#dc2626", textAlign: "center", marginTop: "2rem" },
  empty: { textAlign: "center", color: "#9ca3af", padding: "3rem" },
};

export default styles;
