const styles = {
  page: {
    minHeight: "100vh",
    backgroundColor: "#f0f2f5",
    padding: "2rem",
    fontFamily: "sans-serif",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "2rem",
  },
  title: { fontSize: "1.75rem", fontWeight: 700, color: "#1e1b4b" },
  backBtn: {
    padding: "0.5rem 1rem",
    borderRadius: "8px",
    border: "none",
    background: "#e0e7ff",
    color: "#4f46e5",
    fontWeight: 600,
    cursor: "pointer",
    textDecoration: "none",
    fontSize: "0.9rem",
  },
  layout: {
    display: "grid",
    gridTemplateColumns: "1fr 320px",
    gap: "1.5rem",
    alignItems: "start",
  },
  card: {
    background: "#fff",
    borderRadius: "12px",
    padding: "2rem",
    boxShadow: "0 2px 12px rgba(0,0,0,0.07)",
  },
  cardTitle: { fontSize: "1.1rem", fontWeight: 700, marginBottom: "1.25rem", color: "#374151" },
  form: { display: "flex", flexDirection: "column", gap: "1rem" },
  row: { display: "flex", flexDirection: "column", gap: "0.3rem" },
  label: { fontWeight: 600, fontSize: "0.875rem", color: "#374151" },
  input: {
    padding: "0.65rem 0.9rem",
    borderRadius: "8px",
    border: "1px solid #d1d5db",
    fontSize: "1rem",
    outline: "none",
  },
  textarea: {
    padding: "0.65rem 0.9rem",
    borderRadius: "8px",
    border: "1px solid #d1d5db",
    fontSize: "1rem",
    outline: "none",
    resize: "vertical",
    minHeight: "80px",
  },
  checkRow: { display: "flex", alignItems: "center", gap: "0.6rem" },
  saveBtn: {
    padding: "0.75rem",
    borderRadius: "8px",
    border: "none",
    background: "#4f46e5",
    color: "#fff",
    fontWeight: 600,
    cursor: "pointer",
    fontSize: "1rem",
    marginTop: "0.5rem",
  },
  logoBox: {
    display: "flex",
    flexDirection: "column",
    gap: "0.75rem",
    alignItems: "center",
  },
  logo: {
    width: "140px",
    height: "140px",
    objectFit: "cover",
    borderRadius: "12px",
    border: "2px solid #e5e7eb",
  },
  logoPlaceholder: {
    width: "140px",
    height: "140px",
    borderRadius: "12px",
    background: "#e0e7ff",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "0.85rem",
    color: "#6366f1",
    fontWeight: 600,
  },
  fileInput: { fontSize: "0.875rem" },
  uploadBtn: {
    padding: "0.55rem 1rem",
    borderRadius: "8px",
    border: "none",
    background: "#059669",
    color: "#fff",
    fontWeight: 600,
    cursor: "pointer",
    fontSize: "0.875rem",
  },
  revenueValue: { fontSize: "1.75rem", fontWeight: 700, color: "#4f46e5", marginTop: "0.5rem" },
  error:   { color: "#dc2626", marginBottom: "0.5rem" },
  success: { color: "#059669", marginBottom: "0.5rem" },
};

export default styles;
